import type { QueryResultRow } from "pg";

import { retryDsqlOcc, type DsqlOccRetryOptions } from "./migrate.js";

export type DsqlSchemaPool = {
  query<Row extends QueryResultRow = QueryResultRow>(
    text: string,
    values?: readonly unknown[],
  ): Promise<{ rows: Row[]; rowCount: number | null }>;
};

export type DisposableDsqlSchema = Readonly<{
  name: string;
  cleanup(): Promise<void>;
}>;

export type DisposableDsqlSchemaOptions = Readonly<{
  retry?: DsqlOccRetryOptions;
}>;

/**
 * Creates an isolated schema for an opt-in DSQL suite and guarantees that a
 * failed setup still attempts bounded OCC-aware cleanup. Schema names are
 * generated by each caller, making cleanup safe even after an ambiguous DDL
 * response where the server may have created the schema before reporting OC000.
 */
export async function createDisposableDsqlSchema(
  pool: DsqlSchemaPool,
  name: string,
  options: DisposableDsqlSchemaOptions = {},
): Promise<DisposableDsqlSchema> {
  const identifier = quoteIdentifier(name);
  const drop = () =>
    retryDsqlOcc(
      () => pool.query(`DROP SCHEMA IF EXISTS ${identifier} CASCADE`),
      options.retry,
    );

  try {
    await retryDsqlOcc(() => pool.query(`CREATE SCHEMA ${identifier}`), options.retry);
  } catch (createError) {
    try {
      await drop();
    } catch (cleanupError) {
      throw new AggregateError(
        [createError, cleanupError],
        `Failed to create and clean up disposable DSQL schema ${name}.`,
      );
    }
    throw createError;
  }

  let cleaned = false;
  return Object.freeze({
    name,
    cleanup: async () => {
      if (cleaned) return;
      await drop();
      cleaned = true;
    },
  });
}

function quoteIdentifier(identifier: string): string {
  if (!/^[a-z_][a-z0-9_]*$/u.test(identifier))
    throw new Error("Invalid disposable DSQL schema identifier.");
  return `\"${identifier}\"`;
}
